### ISSUE TITLE
[GPAPI] Add devices for API levels 29 to 34

### ISSUE THREAD

**Issue by codeurimpulsif** [EFForg/rs-google-play#13] opened 2023-12-20 16:16 UTC
Lots of applications don't have an API level inferior to 29 anymore, so we can't download them.

**Comment by gustavi** [comment] 2024-01-08 14:05
If someone has a method to add profiles I have devices to generate some.

**Comment by gustavi** [comment] 2024-01-15 10:35
Some things after take (too many) hours learning Rust and digging the behavior of apkeep/Play Store: I'm quite sure the problem is related to `AppDetails.version_code` which is `None` in response. It prevents APK download (exit occured in `Gpapi.get_latest_version_for_pkg_name` with `GpapiErrorKind::InvalidApp`).

I continue to investigate this. Help is welcome!

**Comment by gustavi** [comment] 2024-01-15 14:03
Main problem identified: https://github.com/EFForg/rs-google-play/blob/master/gpapi/src/consts.rs is used regardless of values in `devices.properties`. I have a patch working, I'll stabilise it during next days and submit a PR. I also have an Android application to spoof phone (based on Aurora Store code) which I may publish to update devices list with contributions.

**Comment by Hainish** [comment] 2024-03-29 03:40
This is fixed as of upgrade to version 3 of Google Play API in https://github.com/EFForg/rs-google-play/commit/6437ac4a8a6003b7407c8ca616703d93a91aee95 and `gpapi` 5.0.0.

**Comment by Hainish** [comment] 2024-03-29 03:40
Thanks!

**Closed by Hainish** 2024-03-29 03:40 UTC
